In [93]:
import pandas as pd

In [94]:
df = pd.read_csv("./Data/Raw/Processed/student.csv")

In [95]:
df

    StudentID            Name  Age   Gender  Course                  Email
0         101    Rahul Sharma   21     Male  Python        rahul@gmail.com
1         102     Priya Verma   22   Female     SQL        priya@gmail.com
2         103      Amit Kumar  NaN     Male   Excel         amit@gmail.com
3         104      Neha Singh   -5   Female  Python         neha@gmail.com
4         105       Rohan Das   23     Male     SQL         rohangmail.com
5         106    Anjali Gupta   20   Female     NaN       anjali@gmail.com
6         107     Vikas Yadav   24        M  Python        vikas@gmail.com
7         108    Pooja Sharma   22   Female     SQL        pooja@gmail.com
8         108    Pooja Sharma   22   Female     SQL        pooja@gmail.com
9         109     Arjun Patel  150     Male   Excel        arjun@gmail.com
10        110     Simran Kaur   21   Female  Python                    NaN
11        111     Karan Mehta   19     Male     SQL        karan@gmail.com
12        112     Ravi Verma    20     Male  Python         ravi@gmail.com
13        113      Sneha Jain  abc   Female   Excel        sneha@gmail.com
14        114    Deepak Singh   22  Unknown     SQL       deepak@gmail.com
15        115     Meera Gupta   23   Female  Python        meera@gmail.com
16        116     Ajay Mishra   25     Male     SQL         ajay@gmail.com
17        117      Ritu Singh   21   Female   Excel         ritu@gmail.com
18        118     Mohit Verma  NaN     Male  Python        mohit@gmail.com
19        119      Kajal Jain   22   Female     NaN        kajal@gmail.com
20        120    Sachin Yadav  -10     Male     SQL       sachin@gmail.com
21        121      Anu Sharma   24        F  Python          anu@gmail.com
22        122    Rakesh Gupta   26     Male   Excel        rakeshgmail.com
23        123      Nikita Das   23   Female     SQL       nikita@gmail.com
24        124    Ashish Kumar  200     Male  Python       ashish@gmail.com
25        125   Pallavi Singh   21   Female   Excel                    NaN
26        126    Manish Patel   22     Male     SQL       manish@gmail.com
27        127   Divya Sharma    20   Female  Python        divya@gmail.com
28        128      Rohit Jain  abc     Male   Excel        rohit@gmail.com
29        129     Sonal Gupta   24   Female     SQL        sonal@gmail.com
30        130     Vivek Verma   23  Unknown  Python        vivek@gmail.com
31        131    Payal Sharma   21   Female   Excel        payal@gmail.com
32        132    Deepak Yadav  NaN     Male     SQL      deepaky@gmail.com
33        133      Ankit Jain   22     Male     NaN        ankit@gmail.com
34        134    Shreya Gupta   19   Female  Python       shreya@gmail.com
35        135    Rahul Sharma   21     Male  Python        rahul@gmail.com
36        136      Neha Verma   -2   Female     SQL   neha.verma@gmail.com
37        137      Aman Singh   24        M   Excel         aman@gmail.com
38        138     Pooja Gupta   23   Female  Python         poojagmail.com
39        139      Ravi Patel   25     Male     SQL   ravi.patel@gmail.com
40        140      Komal Jain   22   Female   Excel        komal@gmail.com
41        141    Suresh Kumar  130     Male  Python       suresh@gmail.com
42        142    Nisha Sharma   21   Female     SQL                    NaN
43        143     Vikas Gupta   20     Male   Excel  vikas.gupta@gmail.com
44        144        Tina Das   22   Female  Python         tina@gmail.com
45        145     Harsh Verma  abc     Male     SQL        harsh@gmail.com
46        146     Megha Singh   24   Female     NaN        megha@gmail.com
47        147      Arun Patel   23  Unknown   Excel         arun@gmail.com
48        148     Ritika Jain   21   Female  Python       ritika@gmail.com
49        149     Karan Mehta   19     Male     SQL        karan@gmail.com
50        150   Aditya Sharma   22     Male  Python       aditya@gmail.com

In [96]:
df.drop_duplicates(inplace=True)

In [127]:
df

    StudentID            Name  Age  Gender  Course                  Email
0         101    Rahul Sharma   21    Male  Python        rahul@gmail.com
1         102     Priya Verma   22  Female     SQL        priya@gmail.com
2         103      Amit Kumar   22    Male   Excel         amit@gmail.com
3         104      Neha Singh   22  Female  Python         neha@gmail.com
4         105       Rohan Das   23    Male     SQL         rohangmail.com
5         106    Anjali Gupta   20  Female     NaN       anjali@gmail.com
6         107     Vikas Yadav   24    Male  Python        vikas@gmail.com
7         108    Pooja Sharma   22  Female     SQL        pooja@gmail.com
8         109     Arjun Patel   22    Male   Excel        arjun@gmail.com
9         110     Simran Kaur   21  Female  Python                    NaN
10        111     Karan Mehta   19    Male     SQL        karan@gmail.com
11        112     Ravi Verma    20    Male  Python         ravi@gmail.com
12        113      Sneha Jain   22  Female   Excel        sneha@gmail.com
13        114    Deepak Singh   22    None     SQL       deepak@gmail.com
14        115     Meera Gupta   23  Female  Python        meera@gmail.com
15        116     Ajay Mishra   25    Male     SQL         ajay@gmail.com
16        117      Ritu Singh   21  Female   Excel         ritu@gmail.com
17        118     Mohit Verma   22    Male  Python        mohit@gmail.com
18        119      Kajal Jain   22  Female     NaN        kajal@gmail.com
19        120    Sachin Yadav   22    Male     SQL       sachin@gmail.com
20        121      Anu Sharma   24  Female  Python          anu@gmail.com
21        122    Rakesh Gupta   26    Male   Excel        rakeshgmail.com
22        123      Nikita Das   23  Female     SQL       nikita@gmail.com
23        124    Ashish Kumar   22    Male  Python       ashish@gmail.com
24        125   Pallavi Singh   21  Female   Excel                    NaN
25        126    Manish Patel   22    Male     SQL       manish@gmail.com
26        127   Divya Sharma    20  Female  Python        divya@gmail.com
27        128      Rohit Jain   22    Male   Excel        rohit@gmail.com
28        129     Sonal Gupta   24  Female     SQL        sonal@gmail.com
29        130     Vivek Verma   23    None  Python        vivek@gmail.com
30        131    Payal Sharma   21  Female   Excel        payal@gmail.com
31        132    Deepak Yadav   22    Male     SQL      deepaky@gmail.com
32        133      Ankit Jain   22    Male     NaN        ankit@gmail.com
33        134    Shreya Gupta   19  Female  Python       shreya@gmail.com
34        135    Rahul Sharma   21    Male  Python        rahul@gmail.com
35        136      Neha Verma   22  Female     SQL   neha.verma@gmail.com
36        137      Aman Singh   24    Male   Excel         aman@gmail.com
37        138     Pooja Gupta   23  Female  Python         poojagmail.com
38        139      Ravi Patel   25    Male     SQL   ravi.patel@gmail.com
39        140      Komal Jain   22  Female   Excel        komal@gmail.com
40        141    Suresh Kumar   22    Male  Python       suresh@gmail.com
41        142    Nisha Sharma   21  Female     SQL                    NaN
42        143     Vikas Gupta   20    Male   Excel  vikas.gupta@gmail.com
43        144        Tina Das   22  Female  Python         tina@gmail.com
44        145     Harsh Verma   22    Male     SQL        harsh@gmail.com
45        146     Megha Singh   24  Female     NaN        megha@gmail.com
46        147      Arun Patel   23    None   Excel         arun@gmail.com
47        148     Ritika Jain   21  Female  Python       ritika@gmail.com
48        149     Karan Mehta   19    Male     SQL        karan@gmail.com
49        150   Aditya Sharma   22    Male  Python       aditya@gmail.com

In [107]:
df["Age"] = pd.to_numeric(df["Age"], errors="coerce")

In [105]:
df.loc[df["Age"] > 50,"Age"] = pd.NA

In [108]:
df["Age"] = df["Age"].fillna(df["Age"].median())

In [111]:
df["Age"] = df["Age"].astype(int)

In [110]:
df.loc[df["Age"] < 0, "Age"] = pd.NA

In [115]:
df["Gender"] = df["Gender"].replace({
    "M": "Male",
    "F": "Female",
    "Unknown": None
})

In [128]:
df["Email"] = df["Email"].replace({"NaN":"None"})

In [141]:
df.head(10)

   StudentID          Name  Age  Gender        Course             Email
0        101  Rahul Sharma   21    Male        Python   rahul@gmail.com
1        102   Priya Verma   22  Female           SQL   priya@gmail.com
2        103    Amit Kumar   22    Male         Excel    amit@gmail.com
3        104    Neha Singh   22  Female        Python    neha@gmail.com
4        105     Rohan Das   23    Male           SQL    rohangmail.com
5        106  Anjali Gupta   20  Female  Not Assigned  anjali@gmail.com
6        107   Vikas Yadav   24    Male        Python   vikas@gmail.com
7        108  Pooja Sharma   22  Female           SQL   pooja@gmail.com
8        109   Arjun Patel   22    Male         Excel   arjun@gmail.com
9        110   Simran Kaur   21  Female        Python          No Email

In [139]:
print(df["Course"].unique())
print(df["Email"].unique())

<StringArray>
['Python', 'SQL', 'Excel', nan]
Length: 4, dtype: str
<StringArray>
[      'rahul@gmail.com',       'priya@gmail.com',        'amit@gmail.com',
        'neha@gmail.com',        'rohangmail.com',      'anjali@gmail.com',
       'vikas@gmail.com',       'pooja@gmail.com',       'arjun@gmail.com',
                     nan,       'karan@gmail.com',        'ravi@gmail.com',
       'sneha@gmail.com',      'deepak@gmail.com',       'meera@gmail.com',
        'ajay@gmail.com',        'ritu@gmail.com',       'mohit@gmail.com',
       'kajal@gmail.com',      'sachin@gmail.com',         'anu@gmail.com',
       'rakeshgmail.com',      'nikita@gmail.com',      'ashish@gmail.com',
      'manish@gmail.com',       'divya@gmail.com',       'rohit@gmail.com',
       'sonal@gmail.com',       'vivek@gmail.com',       'payal@gmail.com',
     'deepaky@gmail.com',       'ankit@gmail.com',      'shreya@gmail.com',
  'neha.verma@gmail.com',        'aman@gmail.com',        'poojagmail.com',
  'ravi.patel@gmail.com',       'komal@gmail.com',      'suresh@gmail.com',
 'vikas.gupta@gmail.com',        'tina@gmail.com',       'harsh@gmail.com',
       'megha@gmail.com',        'arun@gmail.com',      'ritika@gmail.com',
      'aditya@gmail.com']
Length: 46, dtype: str

In [140]:
df["Course"] = df["Course"].replace("", pd.NA)
df["Email"] = df["Email"].replace("", pd.NA)

df["Course"] = df["Course"].fillna("Not Assigned")
df["Email"] = df["Email"].fillna("No Email")

In [150]:
df["Course"] = df["Course"].replace("", pd.NA)
df["Course"] = df["Course"].fillna("Not Assigned")

In [142]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 6 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   StudentID  50 non-null     int64
 1   Name       50 non-null     str
 2   Age        50 non-null     int64
 3   Gender     47 non-null     object
 4   Course     50 non-null     str
 5   Email      50 non-null     str
dtypes: int64(2), object(1), str(3)
memory usage: 2.5+ KB

In [151]:
df.isna().sum()

StudentID    0
Name         0
Age          0
Gender       3
Course       0
Email        0
dtype: int64

In [152]:
df.Gender

0       Male
1     Female
2       Male
3     Female
4       Male
5     Female
6       Male
7     Female
8       Male
9     Female
10      Male
11      Male
12    Female
13      None
14    Female
15      Male
16    Female
17      Male
18    Female
19      Male
20    Female
21      Male
22    Female
23      Male
24    Female
25      Male
26    Female
27      Male
28    Female
29      None
30    Female
31      Male
32      Male
33    Female
34      Male
35    Female
36      Male
37    Female
38      Male
39    Female
40      Male
41    Female
42      Male
43    Female
44      Male
45    Female
46      None
47    Female
48      Male
49      Male
Name: Gender, dtype: object

In [155]:
df.tail(5)

    StudentID           Name  Age  Gender        Course             Email
45        146    Megha Singh   24  Female  Not Assigned   megha@gmail.com
46        147     Arun Patel   23    None         Excel    arun@gmail.com
47        148    Ritika Jain   21  Female        Python  ritika@gmail.com
48        149    Karan Mehta   19    Male           SQL   karan@gmail.com
49        150  Aditya Sharma   22    Male        Python  aditya@gmail.com

In [157]:
df ['Gender']= df['Gender'].fillna('Male')

In [158]:
df.tail(5)

    StudentID           Name  Age  Gender        Course             Email
45        146    Megha Singh   24  Female  Not Assigned   megha@gmail.com
46        147     Arun Patel   23    Male         Excel    arun@gmail.com
47        148    Ritika Jain   21  Female        Python  ritika@gmail.com
48        149    Karan Mehta   19    Male           SQL   karan@gmail.com
49        150  Aditya Sharma   22    Male        Python  aditya@gmail.com

In [159]:
df.to_csv("students_cleaned.csv", index=False)